#! /bin/bash
https://www.google.com/search?q=fatal%3A+remote+origin+already+exists.&ie=utf-8&oe=utf-8&client=firefox-b-ab
for i in *.svg
do
	nombre=$(basename $i .svg)
	echo creando ${nombre}.pdf ...
	inkscape -D -A ${nombre}.pdf $i
done

for i in *.svg
do
	nombre=$(basename $i .svg)
	echo creando ${nombre}.pdf ...
	inkscape -D -A ${nombre}.pdf $i
done


renombra svg con inkskape

for i in *.svg
do
	nombre=$(basename $i .svg)
	echo creando ${nombre}.pdf ...
	inkscape -D -A ${nombre}.pdf $i
done

if [ ! -d pdfs ] then mkdir pdfs; fi
mv *.pdf pdfs


 cont=0
 nombre="lab2."
 for  i in *.svg
 do
 ((cont=$cont+1))
 nuevonombre=$nombre$cont
 echo "Renombrando... $i"
 echo "a $nuevonombre.svg"
 mv $i $nuevonombre.svg
 done

 
 #! /bin/bash

# renombra svg con inkskape

for i in *.svg
do
	nombre=$(basename $i .svg)
	echo creando ${nombre}.pdf ...
	inkscape -D -A ${nombre}.pdf $i
done

if [ ! -d pdfs ] then mkdir pdfs; fi
mv *.pdf pdfs

for i in *.svg
 do
 inkscape -D -A $i.pdf $i 
 done 
for i in *.svg
do
	nombre=$(basename $i .svg)
	echo creando ${nombre}.pdf ...
	inkscape -D -A ${nombre}.pdf $i
done
